version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  
  pre_build:
    commands:
      - echo skipped on `date`

  build:
    commands:
      - echo Maven Build started on `date`
      - java -version
      - mvn clean package

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - target/hellojava-1.0-SNAPSHOT.jar
    